/* RH_DER_Fisico_Melhorado */

/* 
   Observação:
   Este script assume que o schema rh e os enums já existem.
   Exemplo:
   CREATE SCHEMA IF NOT EXISTS rh;
*/

/* ============================================================
   SCHEMA
   ============================================================ */

CREATE SCHEMA IF NOT EXISTS rh;

/* ============================================================
   ENUMS - RH
   ============================================================ */

CREATE TYPE rh.status_colaborador_enum AS ENUM (
    'ativo',
    'afastado',
    'ferias',
    'desligado'
);

CREATE TYPE rh.tipo_vinculo_enum AS ENUM (
    'clt',
    'temporario',
    'freelancer',
    'estagio',
    'pj'
);

CREATE TYPE rh.tipo_cargo_enum AS ENUM (
    'operacional',
    'lideranca',
    'administrativo'
);

CREATE TYPE rh.tipo_departamento_enum AS ENUM (
    'cozinha',
    'salao',
    'bar',
    'delivery',
    'limpeza',
    'estoque',
    'administrativo',
    'rh',
    'financeiro'
);

CREATE TYPE rh.tipo_unidade_enum AS ENUM (
    'restaurante',
    'cozinha_central',
    'delivery',
    'administrativo'
);

CREATE TYPE rh.status_unidade_enum AS ENUM (
    'ativa',
    'inativa',
    'em_reforma'
);

CREATE TYPE rh.tipo_ausencia_enum AS ENUM (
    'falta',
    'atestado',
    'ferias',
    'licenca',
    'afastamento',
    'atraso'
);

CREATE TYPE rh.status_aprovacao_enum AS ENUM (
    'pendente',
    'aprovada',
    'recusada'
);

CREATE TYPE rh.tipo_movimentacao_enum AS ENUM (
    'admissao',
    'promocao',
    'transferencia',
    'alteracao_salarial',
    'desligamento',
    'afastamento',
    'retorno_afastamento'
);

CREATE TYPE rh.status_vaga_enum AS ENUM (
    'aberta',
    'pausada',
    'encerrada',
    'cancelada'
);

CREATE TYPE rh.origem_candidatura_enum AS ENUM (
    'site',
    'indicacao',
    'redes_sociais',
    'presencial',
    'agencia',
    'outro'
);

CREATE TYPE rh.status_candidatura_enum AS ENUM (
    'em_analise',
    'aprovada',
    'recusada',
    'desistente',
    'contratada'
);

CREATE TYPE rh.etapa_candidatura_enum AS ENUM (
    'triagem',
    'entrevista',
    'teste',
    'documentacao',
    'finalizada'
);

CREATE TYPE rh.tipo_treinamento_enum AS ENUM (
    'integracao',
    'seguranca',
    'atendimento',
    'boas_praticas',
    'operacional'
);

CREATE TYPE rh.status_participacao_treinamento_enum AS ENUM (
    'pendente',
    'concluido',
    'vencido',
    'cancelado'
);

/* ============================================================
   TABELAS BASE
   ============================================================ */

CREATE TABLE rh.unidade_restaurante (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_unidade varchar(100) NOT NULL,
    tipo_unidade rh.tipo_unidade_enum NOT NULL,
    cidade varchar(100) NOT NULL,
    estado char(2) NOT NULL,
    status rh.status_unidade_enum NOT NULL,

    CONSTRAINT ck_unidade_restaurante_estado
        CHECK (estado ~ '^[A-Z]{2}$')
);

CREATE TABLE rh.cargo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cargo varchar(100) NOT NULL,
    nivel varchar(50),
    descricao text,
    tipo_cargo rh.tipo_cargo_enum NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    salario_base numeric(10,2),
    faixa_salarial_min numeric(10,2),
    faixa_salarial_max numeric(10,2),

    CONSTRAINT ck_cargo_salario_base
        CHECK (salario_base IS NULL OR salario_base >= 0),

    CONSTRAINT ck_cargo_faixa_salarial_min
        CHECK (faixa_salarial_min IS NULL OR faixa_salarial_min >= 0),

    CONSTRAINT ck_cargo_faixa_salarial_max
        CHECK (faixa_salarial_max IS NULL OR faixa_salarial_max >= 0),

    CONSTRAINT ck_cargo_faixa_salarial_valida
        CHECK (
            faixa_salarial_min IS NULL
            OR faixa_salarial_max IS NULL
            OR faixa_salarial_min <= faixa_salarial_max
        )
);

CREATE TABLE rh.turno (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_turno varchar(80) NOT NULL,
    hora_inicio time NOT NULL,
    hora_fim time NOT NULL,
    descricao text,
    ativo boolean NOT NULL DEFAULT true,
    carga_horaria_semanal numeric(5,2),

    CONSTRAINT ck_turno_carga_horaria_semanal
        CHECK (
            carga_horaria_semanal IS NULL 
            OR carga_horaria_semanal > 0
        )
);

CREATE TABLE rh.departamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_departamento varchar(100) NOT NULL,
    ativo boolean NOT NULL DEFAULT true,
    tipo_departamento rh.tipo_departamento_enum NOT NULL,
    descricao text,
    unidade_id bigint NOT NULL,

    CONSTRAINT fk_departamento_unidade_possui
        FOREIGN KEY (unidade_id)
        REFERENCES rh.unidade_restaurante(id)
        ON DELETE RESTRICT
);


/* ============================================================
   COLABORADOR
   ============================================================ */

CREATE TABLE rh.colaborador (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    telefone varchar(20),
    data_admissao date NOT NULL,
    status rh.status_colaborador_enum NOT NULL,
    tipo_vinculo rh.tipo_vinculo_enum NOT NULL,
    email varchar(200),
    cpf char(11) NOT NULL,
    matricula varchar(30) NOT NULL,
    data_nascimento date,
    salario_atual numeric(10,2),
    data_desligamento date,
    observacao text,

    gerente_id bigint,
    cargo_id bigint NOT NULL,
    departamento_id bigint NOT NULL,
    turno_id bigint,

    CONSTRAINT uq_colaborador_cpf
        UNIQUE (cpf),

    CONSTRAINT uq_colaborador_matricula
        UNIQUE (matricula),

    CONSTRAINT uq_colaborador_email
        UNIQUE (email),

    CONSTRAINT ck_colaborador_cpf
        CHECK (cpf ~ '^[0-9]{11}$'),

    CONSTRAINT ck_colaborador_salario_atual
        CHECK (salario_atual IS NULL OR salario_atual >= 0),

    CONSTRAINT ck_colaborador_data_desligamento
        CHECK (
            data_desligamento IS NULL 
            OR data_desligamento >= data_admissao
        ),

    CONSTRAINT ck_colaborador_gerente_diferente
        CHECK (
            gerente_id IS NULL 
            OR gerente_id <> id
        ),

    CONSTRAINT fk_colaborador_colaborador_gerencia
        FOREIGN KEY (gerente_id)
        REFERENCES rh.colaborador(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_colaborador_cargo_ocupa
        FOREIGN KEY (cargo_id)
        REFERENCES rh.cargo(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_colaborador_departamento_alocado
        FOREIGN KEY (departamento_id)
        REFERENCES rh.departamento(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_colaborador_turno_cumpre
        FOREIGN KEY (turno_id)
        REFERENCES rh.turno(id)
        ON DELETE RESTRICT
);


/* ============================================================
   AUSÊNCIA
   ============================================================ */

CREATE TABLE rh.ausencia (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_ausencia rh.tipo_ausencia_enum NOT NULL,
    status_aprovacao rh.status_aprovacao_enum NOT NULL,
    motivo text,
    observacao text,
    data_aprovacao date,
    data_solicitacao date NOT NULL DEFAULT current_date,
    data_inicio date NOT NULL,
    data_fim date NOT NULL,

    colaborador_id bigint NOT NULL,
    aprovador_id bigint,

    CONSTRAINT ck_ausencia_periodo
        CHECK (data_fim >= data_inicio),

    CONSTRAINT fk_ausencia_colaborador_registra
        FOREIGN KEY (colaborador_id)
        REFERENCES rh.colaborador(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_ausencia_colaborador_aprova
        FOREIGN KEY (aprovador_id)
        REFERENCES rh.colaborador(id)
        ON DELETE RESTRICT
);


/* ============================================================
   MOVIMENTAÇÃO DO COLABORADOR
   ============================================================ */

CREATE TABLE rh.movimentacao_colaborador (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_movimentacao rh.tipo_movimentacao_enum NOT NULL,
    data_movimentacao date NOT NULL DEFAULT current_date,
    data_efetivacao date,
    salario_novo numeric(10,2),
    salario_anterior numeric(10,2),
    motivo text,
    observacao text,

    colaborador_id bigint NOT NULL,
    cargo_anterior_id bigint,
    cargo_novo_id bigint,
    departamento_origem_id bigint,
    departamento_destino_id bigint,

    CONSTRAINT ck_movimentacao_salario_anterior
        CHECK (salario_anterior IS NULL OR salario_anterior >= 0),

    CONSTRAINT ck_movimentacao_salario_novo
        CHECK (salario_novo IS NULL OR salario_novo >= 0),

    CONSTRAINT fk_movimentacao_colaborador_colaborador_associada
        FOREIGN KEY (colaborador_id)
        REFERENCES rh.colaborador(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacao_colaborador_cargo_tinha
        FOREIGN KEY (cargo_anterior_id)
        REFERENCES rh.cargo(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacao_colaborador_cargo_assume
        FOREIGN KEY (cargo_novo_id)
        REFERENCES rh.cargo(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacao_colaborador_departamento_sai_de
        FOREIGN KEY (departamento_origem_id)
        REFERENCES rh.departamento(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_movimentacao_colaborador_departamento_vai_para
        FOREIGN KEY (departamento_destino_id)
        REFERENCES rh.departamento(id)
        ON DELETE RESTRICT
);


/* ============================================================
   TREINAMENTO
   ============================================================ */

CREATE TABLE rh.treinamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_treinamento varchar(150) NOT NULL,
    tipo_treinamento rh.tipo_treinamento_enum NOT NULL,
    obrigatorio boolean NOT NULL DEFAULT false,
    validade_meses integer,
    descricao text,
    ativo boolean NOT NULL DEFAULT true,

    CONSTRAINT ck_treinamento_validade_meses
        CHECK (
            validade_meses IS NULL 
            OR validade_meses >= 0
        )
);

CREATE TABLE rh.participacao_treinamento (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status rh.status_participacao_treinamento_enum NOT NULL,
    data_validade date,
    nota numeric(5,2),
    data_realizacao date NOT NULL,
    observacao text,

    colaborador_id bigint NOT NULL,
    treinamento_id bigint NOT NULL,

    CONSTRAINT ck_participacao_treinamento_nota
        CHECK (
            nota IS NULL 
            OR nota BETWEEN 0 AND 100
        ),

    CONSTRAINT uq_participacao_treinamento_colab_trein_data
        UNIQUE (colaborador_id, treinamento_id, data_realizacao),

    CONSTRAINT fk_participacao_treinamento_colaborador_participa
        FOREIGN KEY (colaborador_id)
        REFERENCES rh.colaborador(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_participacao_treinamento_treinamento_refere_se
        FOREIGN KEY (treinamento_id)
        REFERENCES rh.treinamento(id)
        ON DELETE RESTRICT
);


/* ============================================================
   RECRUTAMENTO
   ============================================================ */

CREATE TABLE rh.recrutamento_vaga (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo varchar(150) NOT NULL,
    descricao text,
    requisitos text,
    data_abertura date NOT NULL DEFAULT current_date,
    data_fechamento date,
    status rh.status_vaga_enum NOT NULL,
    quantidade_vagas integer NOT NULL,
    tipo_vinculo rh.tipo_vinculo_enum NOT NULL,
    salario_ofertado numeric(10,2),

    departamento_id bigint NOT NULL,
    turno_id bigint,

    CONSTRAINT ck_recrutamento_vaga_quantidade
        CHECK (quantidade_vagas > 0),

    CONSTRAINT ck_recrutamento_vaga_salario
        CHECK (
            salario_ofertado IS NULL 
            OR salario_ofertado >= 0
        ),

    CONSTRAINT ck_recrutamento_vaga_datas
        CHECK (
            data_fechamento IS NULL 
            OR data_fechamento >= data_abertura
        ),

    CONSTRAINT fk_recrutamento_vaga_departamento_oferta
        FOREIGN KEY (departamento_id)
        REFERENCES rh.departamento(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_recrutamento_vaga_turno_preve
        FOREIGN KEY (turno_id)
        REFERENCES rh.turno(id)
        ON DELETE RESTRICT
);

CREATE TABLE rh.candidato (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(150) NOT NULL,
    email varchar(150) NOT NULL,
    telefone varchar(20),
    data_cadastro date NOT NULL DEFAULT current_date,

    CONSTRAINT uq_candidato_email
        UNIQUE (email)
);

CREATE TABLE rh.candidatura (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_candidatura date NOT NULL DEFAULT current_date,
    origem_candidatura rh.origem_candidatura_enum NOT NULL,
    status_candidatura rh.status_candidatura_enum NOT NULL,
    etapa_atual rh.etapa_candidatura_enum NOT NULL,
    observacao text,
    pretensao_salarial numeric(10,2),

    vaga_id bigint NOT NULL,
    candidato_id bigint NOT NULL,

    CONSTRAINT ck_candidatura_pretensao_salarial
        CHECK (
            pretensao_salarial IS NULL 
            OR pretensao_salarial >= 0
        ),

    CONSTRAINT uq_candidatura_vaga_candidato
        UNIQUE (vaga_id, candidato_id),

    CONSTRAINT fk_candidatura_recrutamento_vaga_recebe
        FOREIGN KEY (vaga_id)
        REFERENCES rh.recrutamento_vaga(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_candidatura_candidato_realiza
        FOREIGN KEY (candidato_id)
        REFERENCES rh.candidato(id)
        ON DELETE RESTRICT
);


/* ============================================================
   ÍNDICES PARA FOREIGN KEYS
   ============================================================ */

CREATE INDEX idx_departamento_unidade_id
    ON rh.departamento(unidade_id);

CREATE INDEX idx_colaborador_gerente_id
    ON rh.colaborador(gerente_id);

CREATE INDEX idx_colaborador_cargo_id
    ON rh.colaborador(cargo_id);

CREATE INDEX idx_colaborador_departamento_id
    ON rh.colaborador(departamento_id);

CREATE INDEX idx_colaborador_turno_id
    ON rh.colaborador(turno_id);

CREATE INDEX idx_ausencia_colaborador_id
    ON rh.ausencia(colaborador_id);

CREATE INDEX idx_ausencia_aprovador_id
    ON rh.ausencia(aprovador_id);

CREATE INDEX idx_movimentacao_colaborador_id
    ON rh.movimentacao_colaborador(colaborador_id);

CREATE INDEX idx_movimentacao_cargo_anterior_id
    ON rh.movimentacao_colaborador(cargo_anterior_id);

CREATE INDEX idx_movimentacao_cargo_novo_id
    ON rh.movimentacao_colaborador(cargo_novo_id);

CREATE INDEX idx_movimentacao_departamento_origem_id
    ON rh.movimentacao_colaborador(departamento_origem_id);

CREATE INDEX idx_movimentacao_departamento_destino_id
    ON rh.movimentacao_colaborador(departamento_destino_id);

CREATE INDEX idx_participacao_treinamento_colaborador_id
    ON rh.participacao_treinamento(colaborador_id);

CREATE INDEX idx_participacao_treinamento_treinamento_id
    ON rh.participacao_treinamento(treinamento_id);

CREATE INDEX idx_recrutamento_vaga_departamento_id
    ON rh.recrutamento_vaga(departamento_id);

CREATE INDEX idx_recrutamento_vaga_turno_id
    ON rh.recrutamento_vaga(turno_id);

CREATE INDEX idx_candidatura_vaga_id
    ON rh.candidatura(vaga_id);

CREATE INDEX idx_candidatura_candidato_id
    ON rh.candidatura(candidato_id);

